NODES_TYPES = [
    'BooleanNodeType',
    'ColorNodeType',
    'ColorCombineNodeType',
    'ColorPaletteNodeType',
    'ColorSplitNodeType',
    'ConditionNodeType',
    'DataInputNodeType',
    'DataOutputNodeType',
    'DebugNodeType',
    'DistanceNodeType',
    'ExpressionNodeType',
    'FloatNumberNodeType',
    'FloatSwitchNodeType',
    'FloatToIntNodeType',
    'FloatToStringNodeType',
    'IntToFloatNodeType',
    'IntegerNodeType',
    'NoteNodeType',
    'ObjectPropertiesNodeType',
    'RenderNodeType',
    'RenderEngineNodeType',
    'RoundFloatNodeType',
    'TimeNodeType',
    'VectorNodeType',
    'VectorSplitNodeType',
    'ViewLayerNodeType']

DATA_ITEMS = (
    ('actions', 'actions', ''),
    ('armatures', 'armatures', ''),
    ('brushes', 'brushes', ''),
    ('cameras', 'cameras', ''),
    ('curves', 'curves', ''),
    ('fonts', 'fonts', ''),
    ('groups', 'groups', ''),
    ('images', 'images', ''),
    ('lamps', 'lamps', ''),
    ('lattices', 'lattices', ''),
    ('linestyles', 'linestyles', ''),
    ('masks', 'masks', ''),
    ('materials', 'materials', ''),
    ('meshes', 'meshes', ''),
    ('metaballs', 'metaballs', ''),
    ('movieclips', 'movieclips', ''),
    ('node_groups', 'node_groups', ''),
    ('objects', 'objects', ''),
    ('particles', 'particles', ''),
    ('scenes', 'scenes', ''),
    ('shape_keys', 'shape_keys', ''),
    ('sounds', 'sounds', ''),
    ('speakers', 'speakers', ''),
    ('texts', 'texts', ''),
    ('textures', 'textures', ''),
    ('worlds', 'worlds', ''))
